# Generated by Django 4.0.4 on 2022-04-29 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('Opening', 'Task is opening'), ('In progress', 'Task in progress'), ('Overdue', 'Task is overdue')], default='Opening', max_length=32)),
                ('deadline', models.DateTimeField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todoapp.taskcategory')),
            ],
        ),
    ]
