# Generated by Django 4.0.4 on 2022-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_taskcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Opening', 'Opening'), ('In progress', 'In progress'), ('Overdue', 'Overdue'), ('Done', 'Done')], default='Opening', max_length=32),
        ),
    ]
