# Generated by Django 4.0.4 on 2022-04-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_remove_task_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_priority',
            field=models.IntegerField(default=1),
        ),
    ]
