# Generated by Django 4.0.4 on 2022-04-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_task_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
