# Generated by Django 3.2.13 on 2022-05-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0023_remove_task_highlighted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner',
            new_name='author',
        ),
    ]
