# Generated by Django 3.2.13 on 2022-05-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0024_rename_owner_task_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_priority',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='taskcategory',
            old_name='category_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='taskcategory',
            old_name='category_name',
            new_name='name',
        ),
    ]
